{% set version = "0.18.0" %}
{% set spacy_model = "en_core_web_sm" %}

package:
  name: torchtext
  version: {{ version }}

source:
  url: https://github.com/pytorch/text/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fe4eb4b361388ef7840dcad117ae95b32252db5520c4eb2b3bead627468fbdf2
  patches:
    # don't build pytorch/text/tree/main/third_party; pull in from conda-forge 
    - patches/0001-do-not-build-third_party-libs.patch
    # make sure we install from $PREFIX and into $SP_DIR/torchtext
    - patches/0002-fix-some-CMake-arguments-for-our-infrastructure.patch
    # remove spurious run requirements from installation requirements
    - patches/0003-remove-unnecessary-installation-requirements.patch
    - patches/0004-load-library-from-correct-place.patch
    - patches/0005-don-t-try-to-init-submodules.patch
    - patches/0006-fix-path-inconsistency-in-test.patch

build:
  number: 2
  # no pytorch on windows in conda-forge, see
  # https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32
  skip: true  # [win]
  # to ensure we get the right version without extra suffixes, c.f.
  # https://github.com/pytorch/text/blob/v0.18.0/packaging/pkg_helpers.bash#L114
  script_env:
    - BUILD_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  rpaths:
    - lib/
    - {{ SP_DIR }}/torch/lib
    - {{ SP_DIR }}/torchtext/lib

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - python
    - pip
    - setuptools
    - numpy
    - pytorch
    # from pytorch/text/tree/main/third_party
    - double-conversion
    - libsentencepiece
    - libutf8proc
    - re2
  run:
    - python
    - nltk
    - requests
    - revtok ==0.0.3.1
    - sacremoses
    - spacy
    - tqdm

test:
  requires:
    - pip
    - pytest
    - expecttest
    - parameterized
    - portalocker >=2
    - spacy-model-{{ spacy_model }}
    - torchdata >=0.6
  source_files:
    - test/
  imports:
    - torchtext
    - torchtext.datasets
    - torchtext.data
    - torchtext.nn
    - torchtext.vocab
  commands:
    - pip check
    {% set tests_to_skip = "_not_a_real_test" %}
    # tests with URLs that don't exist anymore, plus some extreme download times (>5min)
    {% set tests_to_skip = tests_to_skip + " or TestVocab" %}

    # run test suite
    - pytest test/torchtext_unittest -v -k "not ({{ tests_to_skip }})" --durations=10
    # don't run "large" integration tests, which might get OOM killed
    - pytest test/integration_tests -v -k "not large" --durations=10

    # test that pip recognizes installation correctly, i.e. without trailing a0; needs to come last due to `exit 0`
    # 'grep -v' inverts the match but returns non-zero exit code if no lines are returned; so we use 'wc -l';
    - if [ 0 -eq $(pip list | grep "{{ version }}a0" | wc -l) ]; then exit 0; else (pip list && exit 1); fi  # [unix]

about:
  home: https://pytorch.org/text
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Data loaders and abstractions for text and NLP
  dev_url: https://github.com/pytorch/text

extra:
  recipe-maintainers:
    - h-vetinari
    - giswqs
